title: "Open Web Governance Challenge"
description: "Build better communities"
logo: /owch-logo.png
permalink: "/stories/:title"
url: https://metagov.github.io/open-web-challenge
relative_permalinks: false

theme: jekyll-theme-minimal
